import { normalizeRoomCode } from '@/services/firebase'

export const ROOM_JOIN_SCHEME = 'mtgcommander:'
const ROOM_JOIN_HOST = 'join'
const ROOM_JOIN_PAYLOAD_MAX_LENGTH = 256

export function createRoomJoinLink(code: string): string {
  const roomCode = normalizeRoomCode(code)
  return `${ROOM_JOIN_SCHEME}//${ROOM_JOIN_HOST}?code=${encodeURIComponent(roomCode)}`
}

export function parseRoomJoinPayload(payload: string): string {
  if (typeof payload !== 'string' || payload.length > ROOM_JOIN_PAYLOAD_MAX_LENGTH) {
    return normalizeRoomCode('')
  }

  const candidate = payload.trim()
  try {
    return normalizeRoomCode(candidate)
  } catch {
    // QR codes generated by the app contain a deep link rather than raw text.
  }

  try {
    const url = new URL(candidate)
    if (url.protocol !== ROOM_JOIN_SCHEME || url.hostname !== ROOM_JOIN_HOST) {
      return normalizeRoomCode('')
    }
    return normalizeRoomCode(url.searchParams.get('code') ?? '')
  } catch {
    return normalizeRoomCode('')
  }
}
