<template>
  <AppModal :is-open="isOpen" :title="isEditing ? t('players.editDeck') : t('players.addDeck')" @close="$emit('close')">
    <ion-list :inset="true">
      <!-- Deck name -->
      <ion-item>
        <ion-input
          v-model="deckName"
          :label="t('players.deckName')"
          label-placement="stacked"
          :placeholder="autoGeneratedName || t('players.deckName')"
          :clear-input="true"
        />
      </ion-item>
    </ion-list>

    <!-- Commander slots -->
    <ion-list :inset="true">
      <ion-list-header>
        <ion-label>{{ t('playerDetail.commanders') }}</ion-label>
      </ion-list-header>

      <template v-for="(commander, index) in commanders" :key="index">
        <ion-item>
          <img
            v-if="commander"
            slot="start"
            :src="commander.imageUri"
            :alt="commander.name"
            class="commander-thumb"
          />
          <ion-label v-if="commander">
            <h2>{{ commander.name }}</h2>
            <p>{{ commander.typeLine }}</p>
          </ion-label>
          <ion-button
            v-if="commander"
            slot="end"
            fill="clear"
            color="danger"
            @click="removeCommander(index)"
          >
            <ion-icon :icon="closeOutline" slot="icon-only" />
          </ion-button>
        </ion-item>
      </template>

      <!-- Add commander slot -->
      <ion-item v-if="commanders.filter(Boolean).length < 2" button @click="startSearch">
        <ion-icon :icon="addOutline" slot="start" color="primary" />
        <ion-label color="primary">{{ t('playerDetail.addCommander') }}</ion-label>
      </ion-item>
    </ion-list>

    <!-- Commander search (inline) -->
    <div v-if="isSearching" class="px-4 pb-4">
      <ion-searchbar
        v-model="searchQuery"
        :placeholder="t('players.searchCommander')"
        :debounce="300"
        @ionInput="onSearchInput"
      />
      <ion-list v-if="suggestions.length > 0" class="search-results">
        <ion-item
          v-for="name in suggestions"
          :key="name"
          button
          @click="selectCard(name)"
        >
          <ion-label>{{ name }}</ion-label>
        </ion-item>
      </ion-list>
      <div v-if="isLoading" class="flex justify-center py-4">
        <ion-spinner />
      </div>
    </div>

    <div class="p-4">
      <ion-button
        expand="block"
        color="primary"
        :disabled="commanders.filter(Boolean).length === 0"
        @click="handleSave"
      >
        {{ t('players.save') }}
      </ion-button>
    </div>
  </AppModal>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  IonList,
  IonListHeader,
  IonItem,
  IonInput,
  IonLabel,
  IonButton,
  IonIcon,
  IonSearchbar,
  IonSpinner,
} from '@ionic/vue'
import { addOutline, closeOutline } from 'ionicons/icons'
import AppModal from '@/components/ui/AppModal.vue'
import { usePlayerRegistryStore, generateDeckName } from '@/stores/playerRegistryStore'
import { useCardSearch } from '@/composables/useCardSearch'
import { getCardImageUrl } from '@/services/scryfall'
import type { CommanderCardSnapshot } from '@/types/playerRegistry'

const props = defineProps<{
  isOpen: boolean
  profileId: string
  deckId?: string
}>()

const emit = defineEmits<{
  close: []
}>()

const { t } = useI18n()
const registryStore = usePlayerRegistryStore()
const { searchQuery, suggestions, selectedCard, isLoading, onSearchInput, selectCard, clearSelection } = useCardSearch()

const deckName = ref('')
const commanders = ref<(CommanderCardSnapshot | null)[]>([])
const isSearching = ref(false)
const isEditing = ref(false)

const autoGeneratedName = computed(() => {
  const validCommanders = commanders.value.filter(Boolean) as CommanderCardSnapshot[]
  return generateDeckName(validCommanders)
})

watch(() => props.isOpen, (open) => {
  if (!open) return
  isSearching.value = false
  clearSelection()

  if (props.deckId) {
    const deck = registryStore.getDeckById(props.profileId, props.deckId)
    if (deck) {
      isEditing.value = true
      deckName.value = deck.name
      commanders.value = [...deck.commanders]
      return
    }
  }
  isEditing.value = false
  deckName.value = ''
  commanders.value = []
})

watch(selectedCard, (card) => {
  if (!card) return
  const snapshot: CommanderCardSnapshot = {
    scryfallId: card.id,
    name: card.name,
    imageUri: getCardImageUrl(card, 'art_crop'),
    colorIdentity: card.color_identity,
    typeLine: card.type_line,
  }
  commanders.value.push(snapshot)
  isSearching.value = false
  clearSelection()
})

function startSearch() {
  isSearching.value = true
  clearSelection()
}

function removeCommander(index: number) {
  commanders.value.splice(index, 1)
}

function handleSave() {
  const validCommanders = commanders.value.filter(Boolean) as CommanderCardSnapshot[]
  if (validCommanders.length === 0) return

  const finalName = deckName.value.trim() || autoGeneratedName.value

  if (isEditing.value && props.deckId) {
    // Update: remove old commanders and replace
    const deck = registryStore.getDeckById(props.profileId, props.deckId)
    if (deck) {
      deck.commanders = validCommanders
      deck.name = finalName
      const profile = registryStore.getProfileById(props.profileId)
      if (profile) profile.updatedAt = Date.now()
    }
  } else {
    registryStore.addDeck(props.profileId, finalName, validCommanders)
  }
  emit('close')
}
</script>

<style scoped>
.commander-thumb {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  object-fit: cover;
}

.search-results {
  max-height: 200px;
  overflow-y: auto;
}
</style>
